name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install -e "."
          pip install "mkdocs<2.0" mkdocs-material "mkdocstrings[python]" \
            mkdocs-gen-files mkdocs-literate-nav mkdocs-section-index black
      - run: mkdocs gh-deploy --force
